apiVersion: apps/v1
kind: Deployment
metadata:
  name: honda-cmm-bash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honda_cmm
  template:
    metadata:
      labels:
        app: honda_cmm
    spec:
      containers:
      - name: honda-cmm-bash
        image: carismoses/stacking-train:latest
        command: ["bash"]
        resources:
          limits:
            cpu: 5
            memory: 20Gi
            nvidia.com/gpu: 1
          requests:
            cpu: 5
            memory: 20Gi
            nvidia.com/gpu: 1
        tty: true
        ports:
        - containerPort: 6006
        envFrom:
        - configMapRef:
            name: object-store
        - configMapRef:
            name: github-key
        - secretRef:
            name: github-key
        - secretRef:
            name: object-store
