apiVersion: batch/v1
kind: Job
metadata:
  name: eval-<EXP>-<P>
spec:
  template:
    spec:
      containers:
      - name: eval-<EXP>-<P>
        image: <DOCKERID>/stacking-eval:latest
        command: ["bash", "eval.sh"]
        resources:
          limits:
            cpu: 5
            memory: 20Gi
            nvidia.com/gpu: 1
          requests:
            cpu: 5
            memory: 20Gi
            nvidia.com/gpu: 1
        ports:
        - containerPort: 6006
        envFrom:
        - configMapRef:
            name: object-store
        - configMapRef:
            name: github-key
        - secretRef:
            name: github-key
        - secretRef:
            name: object-store
        env:
        - name: EXP
          value: "<EXP>"
        - name: PROBLEM
          value: "<P>"
      restartPolicy: Never
  backoffLimit: 4
